# Generated by Django 4.1 on 2022-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[('27', 'mostagane'), ('31', 'oran'), ('48', 'relizan')], max_length=50, null=True)),
                ('zip', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Testify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('age', models.IntegerField(default=0)),
                ('maried', models.BooleanField(default=False)),
                ('pic', models.ImageField(default='', upload_to='firsty/public/upload_file')),
                ('discription', models.TextField(blank=True)),
            ],
        ),
    ]
