# Generated by Django 4.1 on 2023-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID_nama: ')),
                ('content', models.CharField(max_length=50, null=True)),
                ('date', models.BigIntegerField()),
            ],
        ),
    ]
