# Generated by Django 4.1 on 2022-09-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testify',
            name='adreas',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api_v1.adreas'),
        ),
    ]
