# Generated by Django 4.1 on 2022-09-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_testify_adreas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testify',
            name='adreas',
        ),
        migrations.AlterField(
            model_name='testify',
            name='pic',
            field=models.ImageField(default='gg', upload_to='public/upload_file'),
        ),
    ]
